### ISSUE TITLE
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-G0RRV_/smbus2

### ISSUE THREAD

**Issue by elongo** [melopero/Melopero_AMG8833#1]
HI.

when trying to install the melopero_8833 package as indicated in this repository I am getting the following error: 

Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-G0RRV_/smbus2

I have followed all the steps listed here, and wonder what is missing in the installation process.

**Comment by melopero** [comment]
Hi, 

Thank you for contacting us. 
We received your request and will process it soon. 

Kind regards, 
Melopero Team

**Comment by leoli51** [comment]
Hi, 
have you tried updating your setuptools package and/or pip?
To update setuptools pip and wheel : `pip3 install --upgrade setuptools pip wheel`.
Hope this will solve the issue.

**Comment by elongo** [comment]
Hi, thanks for the tip. I tried a couple of fixes for installed packages, but finally the issue was solved, just by using the Raspbian with desktop image (instead of Raspbian Lite) where most packages and graphic capabilities were preinstalled (especially for the thermal_camera_demo.py), as I am expecting to graph and visualize temperatures, and therefore thought that having the full in GUI may facilitate this. 

**NOW, A COUPLE OF QUESTIONS:**
**1)** Now, I have both examples working. However, the output of temperatures_matrix.py is not clear to me and didn't find documentation about it.  That script prints first and get_temperature() and the result is about **24 degrees C**, and then prints get_pixel_temperature_matrix(), but with values of 16-20.

What are the values in the matrix? are both values supposed to be temperature in Degrees Celsius? and if yes why such a big difference? 

See images attached.

![screenshot](https://user-images.githubusercontent.com/23347211/78895189-b03cfe80-7a6e-11ea-8117-070b0e7c4ea4.png)
![output_zoomed](https://user-images.githubusercontent.com/23347211/78895209-b7640c80-7a6e-11ea-9d4b-09ea9d6d1f7c.png)

 **2)** Up to what distance is the AMG_8833 able to detect changes in temperature? Did tests, but after a meter there was pretty much no changes in the image and just a full blue screen.

Thank you for any hints regarding this issues

e

**Comment by leoli51** [comment]
Hi, I read the datasheet again and noticed that the function `get_temperature` was misleading. It read the temperature of a thermistor so it has nothing to do with the pixels temperatures. I changed some function names `get_temperature` -> `get_thermistor_temperature` and updated the repository and the pip version. Thank you for pointing out the issue.
