### ISSUE TITLE
Use of depricated SMBusWrapper. Is not available any more in new smbus2 package

### ISSUE THREAD

**Issue by theyosh** [melopero/Melopero_AMG8833#2]
The latest version of smbus2 https://pypi.org/project/smbus2/ does not have the SMBusWrapper class anymore. And therefore we cannot upgrade smbus2 to the latest version.

https://github.com/kplindegaard/smbus2/commit/013db7b1645c18a594a0736bab9f066faa377ca7#diff-62bacf73901f5a20ff90cd25db09d1d36edb970bc9f248e45dfd5bd93b9b5ed4

Could you fix this in your code?

**Comment by leoli51** [comment]
Hello @theyosh , 
Thank you for your feedback! We do not use the SMBusWrapper anymore and the issue should be fixed.

**Comment by theyosh** [comment]
Yes! It is working. Thanks a lot!
